name: custard-ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/custard/test/**
  pull_request:
    paths-ignore:
      - .github/custard/test/**
  workflow_dispatch:

jobs:
  affected:
    uses: GoogleCloudPlatform/cloud-samples-tools/.github/workflows/affected.yaml@ts-gigapudding
    permissions:
      statuses: write
    with:
      head-sha: ${{ github.event.workflow_run.head_sha || github.sha }}
      config-file: .github/config.jsonc
  lint:
    needs: affected
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        uses: GoogleCloudPlatform/cloud-samples-tools/actions/steps/map-run@ts-gigapudding
        with:
          command: black
          paths: ${{ needs.affected.outputs.paths }}
